<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BhosaleA" failures="0" tests="3" name="amazon_Project1.Project1_Amazon.Testcase15_Cartpage_Withoutlogin" time="394.755" errors="1" timestamp="2025-02-03T07:01:59 IST" skipped="1">
  <testcase classname="amazon_Project1.Project1_Amazon.Testcase15_Cartpage_Withoutlogin" name="cartpage_withoutlogin" time="130.185">
    <error type="java.util.NoSuchElementException">
      <![CDATA[java.util.NoSuchElementException
at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1026)
at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1047)
at amazon_Project1.Project1_Amazon.Product1page_Project1.product(Product1page_Project1.java:46)
at amazon_Project1.Project1_Amazon.Testcase15_Cartpage_Withoutlogin.cartpage_withoutlogin(Testcase15_Cartpage_Withoutlogin.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- cartpage_withoutlogin -->
  <system-out/>
  <testcase classname="amazon_Project1.Project1_Amazon.Testcase15_Cartpage_Withoutlogin" name="cartpage_withoutlogin" time="154.667"/>
  <system-out>
    <![CDATA[result is passed for test=cartpage_withoutlogin]]>
  </system-out>
  <testcase classname="amazon_Project1.Project1_Amazon.Testcase15_Cartpage_Withoutlogin" name="cartpage_withoutlogin" time="109.903">
    <skipped/>
  </testcase> <!-- cartpage_withoutlogin -->
  <system-out/>
</testsuite> <!-- amazon_Project1.Project1_Amazon.Testcase15_Cartpage_Withoutlogin -->
